// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/analytics": {
    params: {};
  };
  "/register": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/analytics" | "/register" | "/login" | "/*";
  };
  "routes/_dashboard.tsx": {
    id: "routes/_dashboard";
    page: "/analytics" | "/";
  };
  "routes/_dashboard.analytics.tsx": {
    id: "routes/_dashboard.analytics";
    page: "/analytics";
  };
  "routes/_dashboard._index.tsx": {
    id: "routes/_dashboard._index";
    page: "/";
  };
  "routes/_auth.tsx": {
    id: "routes/_auth";
    page: "/register" | "/login";
  };
  "routes/_auth.register.tsx": {
    id: "routes/_auth.register";
    page: "/register";
  };
  "routes/_auth.login.tsx": {
    id: "routes/_auth.login";
    page: "/login";
  };
  "routes/$.tsx": {
    id: "routes/$";
    page: "/*";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/_dashboard": typeof import("./app/routes/_dashboard.tsx");
  "routes/_dashboard.analytics": typeof import("./app/routes/_dashboard.analytics.tsx");
  "routes/_dashboard._index": typeof import("./app/routes/_dashboard._index.tsx");
  "routes/_auth": typeof import("./app/routes/_auth.tsx");
  "routes/_auth.register": typeof import("./app/routes/_auth.register.tsx");
  "routes/_auth.login": typeof import("./app/routes/_auth.login.tsx");
  "routes/$": typeof import("./app/routes/$.tsx");
};